Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2204"
    config.vm.network "forwarded_port", guest: 5000, host: 5000
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provider :libvirt do |libvirt|
      libvirt.memory = 1024
      libvirt.cpus = 1
    end

    config.vm.provision "shell", inline: <<-SHELL
      sudo apt update -y
      sudo apt install -y git python3-pip python3-venv nano curl
    SHELL
end