Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.hostname = "flask-ubuntu"

  # ------------------------------
  # МЕРЕЖА
  # ------------------------------
  # Проброс порту Flask: внутрішній порт 5000 у VM => порт 5000 на хості
  # Тобто Flask-додаток, який слухає 0.0.0.0:5000 у VM, буде доступний у браузері хоста на http://localhost:5000
  config.vm.network "forwarded_port", guest: 5000, host: 5000

  # ------------------------------
  # РЕСУРСИ LIBVIRT (KVM)
  # ------------------------------
  # Налаштування для libvirt-провайдера (апаратна віртуалізація KVM)
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 1024
    libvirt.cpus = 1
    libvirt.storage :file, size: "8G"
  end

  # ------------------------------
  # СПІЛЬНА ТЕКСТОВА ПАПКА
  # ------------------------------
  # Vagrant синхронізує поточну директорію (де лежить цей Vagrantfile)
  # із директорією /vagrant у віртуалці.
  #
  # Тут вибрано тип "9p" швидкий спосіб для libvirt.
  # Можно редагувати файли (наприклад main.py) на хості,
  # і зміни миттєво будуть доступні всередині VM у /vagrant.
  config.vm.synced_folder ".", "/vagrant", type: "9p"

  # ------------------------------
  # ПРОВІЖНІНГ (ВСТАНОВЛЕННЯ СОФТУ. Виконання зовнішнього provision-скрипту)
  # ------------------------------
  # Блок виконається автоматично після створення VM.
  # Він оновлює систему, ставить Python, pip, Git, Nano,
  # розгортає Flask-додаток і запускає його у фоні.
  config.vm.provision "shell", path: "provision.sh"
end

